# Generated by Django 4.0.5 on 2022-07-24 12:56

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required', max_length=254, unique=True, validators=[accounts.validators.ValidateEmail], verbose_name='email address'),
        ),
    ]
