# Generated by Django 4.0.5 on 2022-07-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_platform_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platforms', to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=124),
        ),
    ]
