# Generated by Django 4.0.5 on 2022-07-24 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_platform_product_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac3078cc-4fc5-491c-beeb-3f0f359bfc69'), primary_key=True, serialize=False, unique=True),
        ),
    ]
