# Generated by Django 4.0.5 on 2022-07-25 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_src',
            field=models.CharField(default='https://ng.jumia.is/unsafe/fit-in/300x300/filters:fill(white)/product/14/5877411/1.jpg?1130', max_length=614),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to='accounts.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('77fa69fe-43c9-4600-8564-05a23807c018'), primary_key=True, serialize=False, unique=True),
        ),
    ]
