# Generated by Django 4.0.5 on 2022-07-25 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product_img_src_alter_platform_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='infinix', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18929e0a-c13a-4691-8a7f-b8304306cdb1'), primary_key=True, serialize=False, unique=True),
        ),
    ]
